services:
  db:
    image: postgres:16
    container_name: dhes-postgres
    environment:
      POSTGRES_DB: dhes
      POSTGRES_USER: dhes
      POSTGRES_PASSWORD: dhes
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: dhes-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dhes
      SPRING_DATASOURCE_USERNAME: dhes
      SPRING_DATASOURCE_PASSWORD: dhes

  frontend:
    build: ./frontend
    container_name: dhes-frontend
    environment:
      - VITE_HOST=0.0.0.0 # Critical for Vite to accept the proxy connection

  game:
    build:
      context: .
      dockerfile: Game/Dockerfile
    container_name: dhes-game
    depends_on:
      - backend
    ports:
      - "6767:6767"

  apacheshib:
    image: dockerhub.csc.ncsu.edu/ignacioxd/apacheshib-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    environment:
      - SERVER_NAME=localhost
      - LOGIN_PATH=/
      # Frontend Mapping
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=5173
      # Backend Mapping
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - BACKEND_PATH=/api     

volumes:
  db-data: